# The URL the site will be built for
base_url = "https://arya-k.com"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme ="nord"
